name: equatable_analyzer
description: A native analyzer plugin to ensure Equatable props are consistent.
version: 1.1.0
repository: https://github.com/sidlatau/equatable_analyzer

keywords:
  - analyzer-plugin

environment:
  sdk: ^3.11.0

dependencies:
  analysis_server_plugin: ^0.3.23
  analyzer: ^14.0.0
  analyzer_plugin: ^0.14.17

dev_dependencies:
  analyzer_testing: ^0.4.2
  equatable: ^2.0.7
  lints: ^6.0.0
  test: ^1.25.6
  test_reflective_loader: ^0.4.0
